//! End-to-end integration tests for rsmk CLI.

use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use tempfile::TempDir;

#[test]
fn test_cli_help() {
  let mut cmd = Command::cargo_bin("rsmk").unwrap();
  cmd
    .arg("--help")
    .assert()
    .success()
    .stdout(predicate::str::contains("rsmk"))
    .stdout(predicate::str::contains("Compile"));
}

#[test]
fn test_cli_init_scaffolds_content() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");

  let mut cmd_init = Command::cargo_bin("rsmk").unwrap();
  cmd_init
    .arg("init")
    .arg("--name")
    .arg("Jane Doe")
    .arg("--output")
    .arg(&content_file)
    .assert()
    .success()
    .stdout(predicate::str::contains("[PASS]"));

  assert!(content_file.exists());
  let content = fs::read_to_string(&content_file).unwrap();
  assert!(content.contains("Jane Doe"));
  assert!(content.contains("Libertinus Serif"));
  assert!(!content.contains("Linux Libertine"));
}

#[test]
fn test_cli_init_default_scaffolding() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--name")
    .arg("Jane Doe")
    .assert()
    .success()
    .stdout(predicate::str::contains(
      "Initialized new résumé content scaffold",
    ))
    .stdout(predicate::str::contains(
      "Created .gitignore and .gitattributes",
    ))
    .stdout(predicate::str::contains("Created GitHub Actions workflows"));

  assert!(content_file.exists());
  let content = fs::read_to_string(&content_file).unwrap();
  assert!(content.contains("Jane Doe"));
  assert!(content.contains("Libertinus Serif"));

  let gitignore = temp.path().join(".gitignore");
  assert!(gitignore.exists());
  let gitignore_str = fs::read_to_string(gitignore).unwrap();
  assert!(gitignore_str.contains("*.pdf"));
  assert!(gitignore_str.contains(".resumake/"));

  let gitattributes = temp.path().join(".gitattributes");
  assert!(gitattributes.exists());
  let gitattributes_str = fs::read_to_string(gitattributes).unwrap();
  assert!(gitattributes_str.contains("* text=auto eol=lf"));

  let ci_workflow = temp.path().join(".github/workflows/ci.yml");
  assert!(ci_workflow.exists());
  let ci_str = fs::read_to_string(ci_workflow).unwrap();
  assert!(ci_str.contains("# Generated by rsmk"));
  assert!(ci_str.contains("# rsmk:generated sha256="));
  assert!(ci_str.contains("name: CI"));

  let release_workflow = temp.path().join(".github/workflows/release.yml");
  assert!(release_workflow.exists());
  let release_str = fs::read_to_string(release_workflow).unwrap();
  assert!(release_str.contains("# Generated by rsmk"));
  assert!(release_str.contains("# rsmk:generated sha256="));
  assert!(release_str.contains("name: Release"));

  // Check git repo initialized
  assert!(temp.path().join(".git").exists());
}

#[test]
fn test_cli_init_no_git() {
  let temp = TempDir::new().unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--no-git")
    .assert()
    .success()
    .stdout(predicate::str::contains(
      "Initialized new résumé content scaffold",
    ))
    .stdout(predicate::str::contains(
      "Skipping GitHub Actions workflows (--no-git)",
    ));

  assert!(temp.path().join("content.yaml").exists());
  assert!(!temp.path().join(".git").exists());
  assert!(!temp.path().join(".gitignore").exists());
  assert!(!temp.path().join(".gitattributes").exists());
  // Workflows require a git repo; --no-git skips them entirely.
  assert!(!temp.path().join(".github").exists());
}

#[test]
fn test_cli_init_no_git_then_add_workflows_via_update() {
  let temp = TempDir::new().unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--no-git")
    .assert()
    .success();
  assert!(!temp.path().join(".github").exists());

  // The workspace can opt into workflows later without re-scaffolding content.
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--update")
    .assert()
    .success();

  assert!(temp.path().join(".github/workflows/ci.yml").exists());
  assert!(temp.path().join(".github/workflows/release.yml").exists());
}

#[test]
fn test_cli_init_no_workflows() {
  let temp = TempDir::new().unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--no-workflows")
    .assert()
    .success()
    .stdout(predicate::str::contains(
      "Initialized new résumé content scaffold",
    ));

  assert!(temp.path().join("content.yaml").exists());
  assert!(temp.path().join(".gitignore").exists());
  assert!(temp.path().join(".gitattributes").exists());
  assert!(!temp.path().join(".github").exists());
}

#[test]
fn test_cli_init_force_and_collision() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");

  // First run
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--name")
    .arg("Original Name")
    .assert()
    .success();

  assert!(content_file.exists());
  let content = fs::read_to_string(&content_file).unwrap();
  assert!(content.contains("Original Name"));

  // Second run without force should fail
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--name")
    .arg("New Name")
    .assert()
    .failure()
    .stderr(predicate::str::contains("already exists"))
    .stderr(predicate::str::contains("--force"));

  // Run with force should overwrite
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--name")
    .arg("New Name")
    .arg("--force")
    .assert()
    .success();

  let content_updated = fs::read_to_string(&content_file).unwrap();
  assert!(content_updated.contains("New Name"));
  assert!(!content_updated.contains("Original Name"));
}

#[test]
fn test_cli_init_positional_directory_destination() {
  let temp = TempDir::new().unwrap();

  // `rsmk init <dir>` scaffolds content.yaml inside <dir>, creating it.
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("arvin_resume")
    .arg("--name")
    .arg("Arvin Duh")
    .arg("--no-git")
    .arg("--no-workflows")
    .assert()
    .success();

  let scaffold = temp.path().join("arvin_resume").join("content.yaml");
  assert!(scaffold.exists());
  assert!(fs::read_to_string(&scaffold).unwrap().contains("Arvin Duh"));
}

#[test]
fn test_cli_init_positional_and_output_conflict() {
  let temp = TempDir::new().unwrap();
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("some_dir")
    .arg("--output")
    .arg("content.yaml")
    .assert()
    .failure()
    .stderr(predicate::str::contains("cannot be used with"));
}

#[test]
fn test_cli_init_refuses_non_empty_directory() {
  let temp = TempDir::new().unwrap();
  fs::write(temp.path().join("existing.txt"), "keep me").unwrap();

  // A populated target directory is rejected and left untouched.
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--name")
    .arg("Jane Doe")
    .assert()
    .failure()
    .stderr(predicate::str::contains("not empty"))
    .stderr(predicate::str::contains("--force"));

  assert!(!temp.path().join("content.yaml").exists());
  assert!(!temp.path().join(".github").exists());

  // `--force` scaffolds alongside the existing files.
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("init")
    .arg("--name")
    .arg("Jane Doe")
    .arg("--no-git")
    .arg("--no-workflows")
    .arg("--force")
    .assert()
    .success();

  assert!(temp.path().join("content.yaml").exists());
  assert_eq!(
    fs::read_to_string(temp.path().join("existing.txt")).unwrap(),
    "keep me"
  );
}

#[test]
fn test_cli_init_then_build_succeeds_end_to_end() {
  // Regression test: the default `init` scaffold must actually compile.
  // Earlier versions emitted <bulletinfo> probes without a required `id`
  // field, which made `build`/`build --check` fail on every real resume
  // (i.e. any content with bullets) despite `init` succeeding in isolation.
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");

  Command::cargo_bin("rsmk")
    .unwrap()
    .arg("init")
    .arg("--name")
    .arg("Jane Doe")
    .arg("--output")
    .arg(&content_file)
    .assert()
    .success();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--check")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .success()
    .stdout(predicate::str::contains("SUCCESS"));
}

#[test]
fn test_cli_check_detects_invalid_yaml() {
  let temp = TempDir::new().unwrap();
  let invalid_file = temp.path().join("invalid.yaml");
  fs::write(&invalid_file, "invalid: [yaml").unwrap();

  let mut cmd = Command::cargo_bin("rsmk").unwrap();
  cmd
    .arg("build")
    .arg("--check")
    .arg("--content")
    .arg(&invalid_file)
    .assert()
    .failure()
    .stderr(predicate::str::contains("[FAIL]"));
}

#[test]
fn test_cli_check_fails_on_unrecognized_meta_field() {
  // Regression test for the exact bug that motivated
  // `#[serde(deny_unknown_fields)]` on the model structs: an old
  // `meta.role` (the model now expects `meta.title`) must fail loudly
  // instead of silently vanishing.
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");
  fs::write(
    &content_file,
    r#"
meta:
  name: "Jane Doe"
  version: "1.0.0"
  role: "Staff Engineer"
  contact:
    - name: "jane@example.com"
sections: []
"#,
  )
  .unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--check")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .failure()
    .stderr(predicate::str::contains("role"));
}

#[test]
fn test_cli_check_succeeds_with_meta_extra() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");
  fs::write(
    &content_file,
    r#"
meta:
  name: "Jane Doe"
  version: "1.0.0"
  contact:
    - name: "jane@example.com"
  extra:
    clearance: "Secret"
    relocation: false
    custom_metrics:
      github_followers: 500
sections: []
"#,
  )
  .unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--check")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .success()
    .stdout(predicate::str::contains("SUCCESS"));
}

#[test]
fn test_cli_template_list() {
  let temp = TempDir::new().unwrap();

  let mut cmd = Command::cargo_bin("rsmk").unwrap();
  cmd
    .current_dir(temp.path())
    .arg("template")
    .arg("list")
    .assert()
    .success()
    .stdout(predicate::str::contains("Available templates:"))
    .stdout(predicate::str::contains("classic (built-in, default)"));

  // Add custom template in ./templates/
  let custom_tpl_dir = temp.path().join("templates").join("custom_theme");
  fs::create_dir_all(&custom_tpl_dir).unwrap();

  let mut cmd2 = Command::cargo_bin("rsmk").unwrap();
  cmd2
    .current_dir(temp.path())
    .arg("template")
    .arg("list")
    .assert()
    .success()
    .stdout(predicate::str::contains("classic (built-in, default)"))
    .stdout(predicate::str::contains("custom_theme (custom)"));
}

#[test]
fn test_cli_template_eject_classic() {
  let temp = TempDir::new().unwrap();

  let mut cmd = Command::cargo_bin("rsmk").unwrap();
  cmd
    .current_dir(temp.path())
    .arg("template")
    .arg("eject")
    .arg("classic")
    .assert()
    .success()
    .stdout(predicate::str::contains(
      "✓ Ejected template 'classic' to ./templates/classic/",
    ))
    .stdout(predicate::str::contains("main.typ"))
    .stdout(predicate::str::contains("tokens.typ"))
    .stdout(predicate::str::contains("primitives.typ"))
    .stdout(predicate::str::contains("blocks/experience.typ"))
    .stdout(predicate::str::contains(
      "Run `rsmk build --template ./templates/classic/main.typ` to compile with your local template.",
    ));

  let target_dir = temp.path().join("templates").join("classic");
  assert!(target_dir.join("main.typ").exists());
  assert!(target_dir.join("tokens.typ").exists());
  assert!(target_dir.join("primitives.typ").exists());
  assert!(target_dir.join("blocks").join("experience.typ").exists());
}

#[test]
fn test_cli_template_eject_collision_without_force() {
  let temp = TempDir::new().unwrap();

  // First eject
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("template")
    .arg("eject")
    .arg("classic")
    .assert()
    .success();

  // Second eject without force should fail
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("template")
    .arg("eject")
    .arg("classic")
    .assert()
    .failure()
    .stderr(predicate::str::contains("already exists"))
    .stderr(predicate::str::contains("--force"));

  // Eject with force should succeed
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("template")
    .arg("eject")
    .arg("classic")
    .arg("--force")
    .assert()
    .success()
    .stdout(predicate::str::contains("✓ Ejected template 'classic'"));
}

#[test]
fn test_cli_template_eject_unknown_template() {
  let temp = TempDir::new().unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("template")
    .arg("eject")
    .arg("nonexistent")
    .assert()
    .failure()
    .stderr(predicate::str::contains("Unknown template 'nonexistent'"));
}

#[test]
fn test_cli_build_and_check_flags_integration() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");
  let output_pdf = temp.path().join("custom_resume.pdf");

  // 1. Scaffold content
  Command::cargo_bin("rsmk")
    .unwrap()
    .arg("init")
    .arg("--name")
    .arg("Jane Doe")
    .arg("--output")
    .arg(&content_file)
    .assert()
    .success();

  // 2. rsmk build (standard compilation to custom output)
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--content")
    .arg(&content_file)
    .arg("--output")
    .arg(&output_pdf)
    .assert()
    .success()
    .stdout(predicate::str::contains("SUCCESS"));

  assert!(output_pdf.exists());

  // 3. rsmk build --check
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--check")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .success()
    .stdout(predicate::str::contains("[dry-run: no PDF written]"))
    .stdout(predicate::str::contains("Dry-run check passed"));

  // 4. rsmk build -c
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("-c")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .success()
    .stdout(predicate::str::contains("[dry-run: no PDF written]"))
    .stdout(predicate::str::contains("Dry-run check passed"));

  // 5. rsmk build --template classic
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--template")
    .arg("classic")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .success()
    .stdout(predicate::str::contains("SUCCESS"));

  // 6. Bare rsmk with no subcommand defaults to build
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .assert()
    .success()
    .stdout(predicate::str::contains("SUCCESS"));
}

fn setup_git_repo_with_remote(
  dir: &std::path::Path,
  content_yaml: &str,
) -> std::path::PathBuf {
  let origin_dir = dir.join("remote.git");
  let work_dir = dir.join("repo");
  fs::create_dir_all(&origin_dir).unwrap();
  fs::create_dir_all(&work_dir).unwrap();

  // 1. Init bare remote
  std::process::Command::new("git")
    .arg("init")
    .arg("--bare")
    .current_dir(&origin_dir)
    .output()
    .unwrap();

  // 2. Init work repo
  std::process::Command::new("git")
    .arg("init")
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["config", "user.name", "Test User"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["config", "user.email", "test@example.com"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["config", "commit.gpgsign", "false"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  // Add remote origin
  let origin_path_str = origin_dir.to_str().unwrap();
  std::process::Command::new("git")
    .args(["remote", "add", "origin", origin_path_str])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  // Write content.yaml
  let content_file = work_dir.join("content.yaml");
  fs::write(&content_file, content_yaml).unwrap();

  // Commit and push
  std::process::Command::new("git")
    .args(["add", "."])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["commit", "-m", "chore: initial commit"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["branch", "-M", "main"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["push", "-u", "origin", "main"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  work_dir
}

const SAMPLE_CONTENT: &str = r#"
meta:
  name: "Jane Doe"
  version: "1.2.0"
  contact:
    - name: "jane@example.com"
sections: []
"#;

#[test]
fn test_cli_release_dry_run_success() {
  let temp = TempDir::new().unwrap();
  let work_dir = setup_git_repo_with_remote(temp.path(), SAMPLE_CONTENT);

  // Add prior tag v1.1.0
  std::process::Command::new("git")
    .args(["tag", "-a", "v1.1.0", "-m", "v1.1.0"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["push", "origin", "v1.1.0"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--dry-run")
    .arg("--skip-build")
    .assert()
    .success()
    .stdout(predicate::str::contains("Résumé Release v1.2.0"))
    .stdout(predicate::str::contains("working tree clean"))
    .stdout(predicate::str::contains(
      "upstream branch synced (nothing unpushed)",
    ))
    .stdout(predicate::str::contains("v1.2.0 is new, ahead of v1.1.0"))
    .stdout(predicate::str::contains(
      "pre-flight check skipped (--skip-build)",
    ));

  // Verify tag v1.2.0 was not created in dry-run
  let tags_out = std::process::Command::new("git")
    .args(["tag", "-l"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  let tags_str = String::from_utf8_lossy(&tags_out.stdout);
  assert!(!tags_str.contains("v1.2.0"));
}

#[test]
fn test_cli_release_dirty_working_tree_fails() {
  let temp = TempDir::new().unwrap();
  let work_dir = setup_git_repo_with_remote(temp.path(), SAMPLE_CONTENT);

  // Dirty the tree with an untracked file
  fs::write(work_dir.join("untracked.txt"), "dirty").unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--dry-run")
    .arg("--skip-build")
    .assert()
    .failure()
    .stderr(predicate::str::contains("uncommitted changes"));
}

#[test]
fn test_cli_release_invalid_semver_fails() {
  let temp = TempDir::new().unwrap();
  let invalid_content = r#"
meta:
  name: "Jane Doe"
  version: "not-a-semver"
  contact:
    - name: "jane@example.com"
sections: []
"#;
  let work_dir = setup_git_repo_with_remote(temp.path(), invalid_content);

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--dry-run")
    .arg("--skip-build")
    .assert()
    .failure()
    .stderr(predicate::str::contains("Invalid semver"));
}

#[test]
fn test_cli_release_semver_monotonicity_fails() {
  let temp = TempDir::new().unwrap();
  let work_dir = setup_git_repo_with_remote(temp.path(), SAMPLE_CONTENT); // v1.2.0

  // Add higher tag v1.3.0
  std::process::Command::new("git")
    .args(["tag", "-a", "v1.3.0", "-m", "v1.3.0"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["push", "origin", "v1.3.0"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--dry-run")
    .arg("--skip-build")
    .assert()
    .failure()
    .stderr(predicate::str::contains("semver monotonicity check failed"));
}

#[test]
fn test_cli_release_unpushed_commits_fails() {
  let temp = TempDir::new().unwrap();
  let work_dir = setup_git_repo_with_remote(temp.path(), SAMPLE_CONTENT);

  // Make an unpushed commit
  fs::write(work_dir.join("note.txt"), "hello").unwrap();
  std::process::Command::new("git")
    .args(["add", "."])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["commit", "-m", "unpushed"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--dry-run")
    .arg("--skip-build")
    .assert()
    .failure()
    .stderr(predicate::str::contains("unpushed commit"));
}

#[test]
fn test_cli_release_no_upstream_fails() {
  let temp = TempDir::new().unwrap();
  let work_dir = temp.path().join("local_repo");
  fs::create_dir_all(&work_dir).unwrap();

  std::process::Command::new("git")
    .arg("init")
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["config", "user.name", "Test User"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["config", "user.email", "test@example.com"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["config", "commit.gpgsign", "false"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  fs::write(work_dir.join("content.yaml"), SAMPLE_CONTENT).unwrap();
  std::process::Command::new("git")
    .args(["add", "."])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["commit", "-m", "initial"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--dry-run")
    .arg("--skip-build")
    .assert()
    .failure()
    .stderr(predicate::str::contains("upstream"));
}

#[test]
fn test_cli_release_actual_tag_and_push_success() {
  let temp = TempDir::new().unwrap();
  let work_dir = setup_git_repo_with_remote(temp.path(), SAMPLE_CONTENT);

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--skip-build")
    .arg("-m")
    .arg("Release v1.2.0")
    .assert()
    .success()
    .stdout(predicate::str::contains("created tag v1.2.0"))
    .stdout(predicate::str::contains("pushed tag to origin"))
    .stdout(predicate::str::contains("Release workflow triggered:"));

  // Verify tag v1.2.0 exists in work repo
  let tags_out = std::process::Command::new("git")
    .args(["tag", "-l"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  let tags_str = String::from_utf8_lossy(&tags_out.stdout);
  assert!(tags_str.contains("v1.2.0"));

  // Verify tag v1.2.0 exists in bare remote
  let remote_tags_out = std::process::Command::new("git")
    .args(["tag", "-l"])
    .current_dir(temp.path().join("remote.git"))
    .output()
    .unwrap();
  let remote_tags_str = String::from_utf8_lossy(&remote_tags_out.stdout);
  assert!(remote_tags_str.contains("v1.2.0"));
}

#[test]
fn test_cli_init_update_clean_workflows() {
  let temp = TempDir::new().unwrap();
  let dir = temp.path();
  let workflows_dir = dir.join(".github").join("workflows");
  fs::create_dir_all(&workflows_dir).unwrap();

  let ci_path = workflows_dir.join("ci.yml");
  let release_path = workflows_dir.join("release.yml");

  // Old 0.0.1 workflow
  let old_ci_body = resumake::schema::generate_ci_workflow(Some("0.0.1"));
  let old_ci_stamped =
    resumake::init::stamp_provenance_header(&old_ci_body, "0.0.1");
  fs::write(&ci_path, old_ci_stamped).unwrap();

  let old_release_body =
    resumake::schema::generate_release_workflow(Some("0.0.1"));
  let old_release_stamped =
    resumake::init::stamp_provenance_header(&old_release_body, "0.0.1");
  fs::write(&release_path, old_release_stamped).unwrap();

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(dir)
    .arg("init")
    .arg("--update")
    .assert()
    .success()
    .stdout(predicate::str::contains("Updated workflow"));

  let current_version = env!("CARGO_PKG_VERSION");
  let updated_ci = fs::read_to_string(&ci_path).unwrap();
  assert!(updated_ci.contains(&format!("version: \"{current_version}\"")));
  assert!(updated_ci.contains(&format!("Generated by rsmk {current_version}")));

  let updated_release = fs::read_to_string(&release_path).unwrap();
  assert!(updated_release.contains(&format!("version: \"{current_version}\"")));
  assert!(
    updated_release.contains(&format!("Generated by rsmk {current_version}"))
  );
}

#[test]
fn test_cli_init_update_preserving_customized_workflows() {
  let temp = TempDir::new().unwrap();
  let dir = temp.path();
  let workflows_dir = dir.join(".github").join("workflows");
  fs::create_dir_all(&workflows_dir).unwrap();

  let ci_path = workflows_dir.join("ci.yml");
  let customized_ci = "name: Custom CI\non: [push]\njobs:\n  custom:\n    runs-on: ubuntu-latest\n";
  fs::write(&ci_path, customized_ci).unwrap();

  // Run update without force
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(dir)
    .arg("init")
    .arg("--update")
    .assert()
    .success()
    .stderr(predicate::str::contains("local modifications"))
    .stderr(predicate::str::contains("skipping update"))
    .stderr(predicate::str::contains("--- "));

  assert_eq!(fs::read_to_string(&ci_path).unwrap(), customized_ci);

  // Run update with force
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(dir)
    .arg("init")
    .arg("--update")
    .arg("--force")
    .assert()
    .success()
    .stdout(predicate::str::contains("Force updated workflow"));

  let forced_ci = fs::read_to_string(&ci_path).unwrap();
  let current_version = env!("CARGO_PKG_VERSION");
  assert!(forced_ci.contains(&format!("version: \"{current_version}\"")));
  assert!(!forced_ci.contains("Custom CI"));
}

#[test]
fn test_cli_init_update_never_modifies_content_yaml() {
  let temp = TempDir::new().unwrap();
  let dir = temp.path();
  let content_path = dir.join("content.yaml");
  let initial_content =
    "meta:\n  name: \"Preserved Author\"\n  version: \"1.0.0\"\n";
  fs::write(&content_path, initial_content).unwrap();

  let workflows_dir = dir.join(".github").join("workflows");
  fs::create_dir_all(&workflows_dir).unwrap();
  let ci_path = workflows_dir.join("ci.yml");
  let old_ci_body = resumake::schema::generate_ci_workflow(Some("0.0.1"));
  let old_ci_stamped =
    resumake::init::stamp_provenance_header(&old_ci_body, "0.0.1");
  fs::write(&ci_path, old_ci_stamped).unwrap();

  // Run update
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(dir)
    .arg("init")
    .arg("--update")
    .assert()
    .success();

  assert_eq!(fs::read_to_string(&content_path).unwrap(), initial_content);

  // Run update with force
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(dir)
    .arg("init")
    .arg("--update")
    .arg("--force")
    .assert()
    .success();

  assert_eq!(fs::read_to_string(&content_path).unwrap(), initial_content);
}

#[test]
fn test_cli_release_version_skew_warning() {
  let temp = TempDir::new().unwrap();
  let work_dir = setup_git_repo_with_remote(temp.path(), SAMPLE_CONTENT);

  let workflows_dir = work_dir.join(".github").join("workflows");
  fs::create_dir_all(&workflows_dir).unwrap();
  let ci_path = workflows_dir.join("ci.yml");

  // Pinned to old version 0.0.1
  let ci_body = resumake::schema::generate_ci_workflow(Some("0.0.1"));
  fs::write(&ci_path, ci_body).unwrap();

  // Commit workflow
  std::process::Command::new("git")
    .args(["add", "."])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["commit", "-m", "chore: add pinned workflow"])
    .current_dir(&work_dir)
    .output()
    .unwrap();
  std::process::Command::new("git")
    .args(["push", "origin", "main"])
    .current_dir(&work_dir)
    .output()
    .unwrap();

  let current_version = env!("CARGO_PKG_VERSION");
  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(&work_dir)
    .arg("release")
    .arg("--dry-run")
    .arg("--skip-build")
    .assert()
    .success()
    .stderr(predicate::str::contains(format!(
      "warning: Repository workflows pin rsmk 0.0.1, but your local binary is {current_version}."
    )))
    .stderr(predicate::str::contains(
      "Layout telemetry may measure geometry differently in CI."
    ))
    .stderr(predicate::str::contains(
      "Run `rsmk init --update` to synchronize your workflow pin."
    ));
}

#[test]
fn test_cli_build_watch_nonexistent_content_fails() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("nonexistent.yaml");

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--watch")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .failure()
    .stderr(predicate::str::contains("Content file not found"));
}

#[test]
fn test_cli_build_check_watch_nonexistent_content_fails() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("nonexistent.yaml");

  Command::cargo_bin("rsmk")
    .unwrap()
    .current_dir(temp.path())
    .arg("build")
    .arg("--check")
    .arg("--watch")
    .arg("--content")
    .arg(&content_file)
    .assert()
    .failure()
    .stderr(predicate::str::contains("Content file not found"));
}

#[test]
fn test_cli_build_watch_recompiles_on_change() {
  let temp = TempDir::new().unwrap();
  let content_file = temp.path().join("content.yaml");
  let output_pdf = temp.path().join("watch_resume.pdf");

  // Scaffold content
  Command::cargo_bin("rsmk")
    .unwrap()
    .arg("init")
    .arg("--name")
    .arg("Jane Doe")
    .arg("--output")
    .arg(&content_file)
    .assert()
    .success();

  // Spawn rsmk build --watch
  let bin = assert_cmd::cargo::cargo_bin("rsmk");
  let mut child = std::process::Command::new(bin)
    .current_dir(temp.path())
    .args([
      "build",
      "--watch",
      "--content",
      content_file.to_str().unwrap(),
      "--output",
      output_pdf.to_str().unwrap(),
    ])
    .stdout(std::process::Stdio::piped())
    .stderr(std::process::Stdio::piped())
    .spawn()
    .expect("failed to spawn watch process");

  // Wait for initial PDF to be produced and initial build to finish
  let start = std::time::Instant::now();
  while !output_pdf.exists()
    && start.elapsed() < std::time::Duration::from_secs(25)
  {
    std::thread::sleep(std::time::Duration::from_millis(100));
  }
  assert!(
    output_pdf.exists(),
    "Initial PDF was not created by watcher"
  );

  // Give initial build a moment to fully finalize before recording mtime
  std::thread::sleep(std::time::Duration::from_millis(1000));
  let initial_mtime = fs::metadata(&output_pdf).unwrap().modified().unwrap();

  // Modify content.yaml
  let content = fs::read_to_string(&content_file).unwrap();
  let updated_content = content.replace("Jane Doe", "Jane Smith");
  fs::write(&content_file, updated_content).unwrap();

  // Wait for debounce + recompilation (typst compile + telemetry queries can take several seconds under load)
  let wait_start = std::time::Instant::now();
  let mut updated = false;
  while wait_start.elapsed() < std::time::Duration::from_secs(30) {
    if let Ok(meta) = fs::metadata(&output_pdf) {
      if let Ok(mtime) = meta.modified() {
        if mtime > initial_mtime {
          updated = true;
          break;
        }
      }
    }
    std::thread::sleep(std::time::Duration::from_millis(100));
  }

  let _ = child.kill();
  let _ = child.wait();

  assert!(
    updated,
    "Output PDF was not updated after content.yaml modification in watch mode"
  );
}

#[test]
fn test_cli_update_help() {
  Command::cargo_bin("rsmk")
    .unwrap()
    .arg("update")
    .arg("--help")
    .assert()
    .success()
    .stdout(predicate::str::contains("--force"))
    .stdout(predicate::str::contains("--check"));
}

#[test]
fn test_cli_update_check_quiet() {
  Command::cargo_bin("rsmk")
    .unwrap()
    .arg("--quiet")
    .arg("update")
    .arg("--check")
    .assert()
    .success();
}
