//! Filesystem, path normalization, hashing, and unified diff utilities.

use std::path::{Path, PathBuf};

/// Computes the SHA-256 hash of a byte slice and returns it as a lowercase hex string.
pub fn sha256_hex(data: &[u8]) -> String {
  use sha2::{Digest, Sha256};

  let digest = Sha256::digest(data);
  let mut hex = String::with_capacity(digest.len() * 2);
  for byte in digest {
    use std::fmt::Write as _;
    let _ = write!(hex, "{byte:02x}");
  }
  hex
}

/// Adds a provenance header containing the version and SHA-256 hash to workflow YAML content.
pub fn stamp_provenance_header(content: &str, version: &str) -> String {
  let hash = sha256_hex(content.as_bytes());
  format!(
    "# Generated by rsmk {version}. Safe to overwrite unless you have edited it.\n# rsmk:generated sha256={hash}\n\n{content}"
  )
}

/// Extracts the SHA-256 hash from `# rsmk:generated sha256=<HASH>` and the body below the header.
pub fn extract_provenance_and_body(content: &str) -> Option<(&str, &str)> {
  let prefix = "# rsmk:generated sha256=";
  let idx = content.find(prefix)?;
  let after_prefix = &content[idx + prefix.len()..];
  let end_of_line = after_prefix.find('\n').unwrap_or(after_prefix.len());
  let hash = after_prefix[..end_of_line].trim();
  let after_line = if end_of_line < after_prefix.len() {
    &after_prefix[end_of_line + 1..]
  } else {
    ""
  };

  let body = if let Some(stripped) = after_line.strip_prefix("\r\n") {
    stripped
  } else if let Some(stripped) = after_line.strip_prefix('\n') {
    stripped
  } else {
    after_line
  };

  Some((hash, body))
}

/// Generates a standard unified diff between two text documents, labelled
/// `<filename> (current)` and `<filename> (target)`.
pub fn generate_unified_diff(
  filename: &str,
  old_content: &str,
  new_content: &str,
) -> String {
  similar::TextDiff::from_lines(old_content, new_content)
    .unified_diff()
    .header(
      &format!("{filename} (current)"),
      &format!("{filename} (target)"),
    )
    .to_string()
}

/// Normalizes a content file path into a POSIX virtual path relative to root.
pub fn normalize_posix_path(root: &Path, content_path: &Path) -> String {
  if let Ok(rel) = content_path.strip_prefix(root) {
    let s = rel.to_string_lossy().replace('\\', "/");
    let trimmed = s.trim_start_matches('/');
    return format!("/{trimmed}");
  }

  if let (Ok(canon_root), Ok(canon_content)) =
    (root.canonicalize(), content_path.canonicalize())
  {
    if let Ok(rel) = canon_content.strip_prefix(&canon_root) {
      let s = rel.to_string_lossy().replace('\\', "/");
      let trimmed = s.trim_start_matches('/');
      return format!("/{trimmed}");
    }
  }

  if content_path.is_relative() {
    let raw = content_path.to_string_lossy().replace('\\', "/");
    let trimmed = raw
      .trim_start_matches("./")
      .trim_start_matches('/')
      .trim_start_matches('\\');
    return format!("/{trimmed}");
  }

  if let Some(file_name) = content_path.file_name() {
    return format!("/{}", file_name.to_string_lossy());
  }

  "/content.yaml".to_string()
}

/// Finds the project root directory by searching upward for repository or document markers.
pub fn find_project_root() -> PathBuf {
  let mut curr = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
  loop {
    if curr.join("resume.yaml").exists()
      || curr.join("content.yaml").exists()
      || curr.join("Cargo.toml").exists()
      || curr.join(".git").exists()
    {
      return curr;
    }
    if !curr.pop() {
      break;
    }
  }
  PathBuf::from(".")
}

/// Strips the Windows `\\?\` verbatim prefix (and the `UNC\` marker) from a path.
pub fn display_path(path: &Path) -> String {
  let s = path.to_string_lossy();
  #[cfg(windows)]
  {
    if let Some(rest) = s.strip_prefix(r"\\?\UNC\") {
      return format!(r"\\{rest}");
    }
    if let Some(rest) = s.strip_prefix(r"\\?\") {
      return rest.to_string();
    }
  }
  s.into_owned()
}
