//! Filesystem, path normalization, hashing, and unified diff utilities.

use std::path::{Path, PathBuf};

/// Computes the SHA-256 hash of a byte slice and returns it as a lowercase hex string.
pub(crate) fn sha256_hex(data: &[u8]) -> String {
  use sha2::{Digest, Sha256};

  let digest = Sha256::digest(data);
  let mut hex = String::with_capacity(digest.len() * 2);
  for byte in digest {
    use std::fmt::Write as _;
    let _ = write!(hex, "{byte:02x}");
  }
  hex
}

/// Adds a provenance header containing the version and SHA-256 hash to workflow YAML content.
pub fn stamp_provenance_header(content: &str, version: &str) -> String {
  let hash = sha256_hex(content.as_bytes());
  format!(
    "# Generated by rsmk {version}. Safe to overwrite unless you have edited it.\n# rsmk:generated sha256={hash}\n\n{content}"
  )
}

/// Extracts the SHA-256 hash from `# rsmk:generated sha256=<HASH>` and the body below the header.
pub(crate) fn extract_provenance_and_body(
  content: &str,
) -> Option<(&str, &str)> {
  let prefix = "# rsmk:generated sha256=";
  let idx = content.find(prefix)?;
  let after_prefix = &content[idx + prefix.len()..];
  let end_of_line = after_prefix.find('\n').unwrap_or(after_prefix.len());
  let hash = after_prefix[..end_of_line].trim();
  let after_line = if end_of_line < after_prefix.len() {
    &after_prefix[end_of_line + 1..]
  } else {
    ""
  };

  let body = if let Some(stripped) = after_line.strip_prefix("\r\n") {
    stripped
  } else if let Some(stripped) = after_line.strip_prefix('\n') {
    stripped
  } else {
    after_line
  };

  Some((hash, body))
}

/// Generates a standard unified diff between two text documents, labelled
/// `<filename> (current)` and `<filename> (target)`.
pub(crate) fn generate_unified_diff(
  filename: &str,
  old_content: &str,
  new_content: &str,
) -> String {
  similar::TextDiff::from_lines(old_content, new_content)
    .unified_diff()
    .header(
      &format!("{filename} (current)"),
      &format!("{filename} (target)"),
    )
    .to_string()
}

/// Normalizes a content file path into a POSIX virtual path relative to root.
pub(crate) fn normalize_posix_path(root: &Path, content_path: &Path) -> String {
  if let Ok(rel) = content_path.strip_prefix(root) {
    let s = rel.to_string_lossy().replace('\\', "/");
    let trimmed = s.trim_start_matches('/');
    return format!("/{trimmed}");
  }

  if let (Ok(canon_root), Ok(canon_content)) =
    (root.canonicalize(), content_path.canonicalize())
  {
    if let Ok(rel) = canon_content.strip_prefix(&canon_root) {
      let s = rel.to_string_lossy().replace('\\', "/");
      let trimmed = s.trim_start_matches('/');
      return format!("/{trimmed}");
    }
  }

  if content_path.is_relative() {
    let raw = content_path.to_string_lossy().replace('\\', "/");
    let trimmed = raw
      .trim_start_matches("./")
      .trim_start_matches('/')
      .trim_start_matches('\\');
    return format!("/{trimmed}");
  }

  if let Some(file_name) = content_path.file_name() {
    return format!("/{}", file_name.to_string_lossy());
  }

  "/content.yaml".to_string()
}

/// Finds the project root directory by searching upward for repository or document markers.
pub(crate) fn find_project_root() -> PathBuf {
  let mut curr = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
  loop {
    if curr.join("resume.yaml").exists()
      || curr.join("content.yaml").exists()
      || curr.join("Cargo.toml").exists()
      || curr.join(".git").exists()
    {
      return curr;
    }
    if !curr.pop() {
      break;
    }
  }
  PathBuf::from(".")
}

/// Strips the Windows `\\?\` verbatim prefix (and the `UNC\` marker) from a path.
pub(crate) fn display_path(path: &Path) -> String {
  let s = path.to_string_lossy();
  #[cfg(windows)]
  {
    if let Some(rest) = s.strip_prefix(r"\\?\UNC\") {
      return format!(r"\\{rest}");
    }
    if let Some(rest) = s.strip_prefix(r"\\?\") {
      return rest.to_string();
    }
  }
  s.into_owned()
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_sha256_hex() {
    assert_eq!(
      sha256_hex(b""),
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );
    assert_eq!(
      sha256_hex(b"abc"),
      "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
  }

  #[test]
  fn test_stamp_provenance_header() {
    let content = "name: CI\n";
    let stamped = stamp_provenance_header(content, "0.1.0");
    assert!(stamped.contains("# Generated by rsmk 0.1.0."));
    assert!(stamped.contains("# rsmk:generated sha256="));
    assert!(stamped.ends_with("name: CI\n"));
  }

  #[test]
  fn test_extract_provenance_and_body() {
    let content = "name: CI\non: [push]\n";
    let stamped = stamp_provenance_header(content, "0.1.0");
    let (hash, body) = extract_provenance_and_body(&stamped).unwrap();
    assert_eq!(hash, sha256_hex(content.as_bytes()));
    assert_eq!(body, content);

    let stamped_crlf = stamped.replace('\n', "\r\n");
    let (hash_crlf, body_crlf) =
      extract_provenance_and_body(&stamped_crlf).unwrap();
    assert_eq!(hash_crlf, sha256_hex(content.as_bytes()));
    assert_eq!(body_crlf.replace("\r\n", "\n"), content);

    assert_eq!(extract_provenance_and_body("name: CI\n"), None);
  }

  #[test]
  fn test_generate_unified_diff() {
    let old_text = "line1\nline2\nline3\n";
    let new_text = "line1\nline2_modified\nline3\nline4\n";
    let diff = generate_unified_diff("test.yml", old_text, new_text);
    assert!(diff.contains("--- test.yml (current)"));
    assert!(diff.contains("+++ test.yml (target)"));
    assert!(diff.contains("-line2"));
    assert!(diff.contains("+line2_modified"));
    assert!(diff.contains("+line4"));
  }
}
