//! Initialization logic for scaffolding new résumé projects, git repositories,
//! and GitHub Actions workflows.

use crate::schema::{
  generate_ci_workflow, generate_init_template, generate_release_workflow,
};
use crate::ui::{print_error, print_info, print_success};
use std::fs;
use std::io::IsTerminal;
use std::path::Path;

/// Options configuring the workspace initialization process.
#[derive(Debug, Clone)]
pub struct InitOptions<'a> {
  /// Explicit candidate name override.
  pub name: Option<&'a str>,
  /// Destination path for the new content file.
  pub output: &'a Path,
  /// Whether to overwrite existing files.
  pub force: bool,
  /// Whether to skip git repository initialization and git config files.
  pub no_git: bool,
  /// Whether to skip GitHub Actions workflow scaffolding.
  pub no_workflows: bool,
  /// Suppress informational console output.
  pub quiet: bool,
}

/// Computes the SHA-256 hash of a byte slice and returns it as a lowercase hex string.
pub fn sha256_hex(data: &[u8]) -> String {
  const K: [u32; 64] = [
    0x428a_2f98,
    0x7137_4491,
    0xb5c0_fbcf,
    0xe9b5_dba5,
    0x3956_c25b,
    0x59f1_11f1,
    0x923f_82a4,
    0xab1c_5ed5,
    0xd807_aa98,
    0x1283_5b01,
    0x2431_85be,
    0x550c_7dc3,
    0x72be_5d74,
    0x80de_b1fe,
    0x9bdc_06a7,
    0xc19b_f174,
    0xe49b_69c1,
    0xefbe_4786,
    0x0fc1_9dc6,
    0x240c_a1cc,
    0x2de9_2c6f,
    0x4a74_84aa,
    0x5cb0_a9dc,
    0x76f9_88da,
    0x983e_5152,
    0xa831_c66d,
    0xb003_27c8,
    0xbf59_7fc7,
    0xc6e0_0bf3,
    0xd5a7_9147,
    0x06ca_6351,
    0x1429_2967,
    0x27b7_0a85,
    0x2e1b_2138,
    0x4d2c_6dfc,
    0x5338_0d13,
    0x650a_7354,
    0x766a_0abb,
    0x81c2_c92e,
    0x9272_2c85,
    0xa2bf_e8a1,
    0xa81a_664b,
    0xc24b_8b70,
    0xc76c_51a3,
    0xd192_e819,
    0xd699_0624,
    0xf40e_3585,
    0x106a_a070,
    0x19a4_c116,
    0x1e37_6c08,
    0x2748_774c,
    0x34b0_bcb5,
    0x391c_0cb3,
    0x4ed8_aa4a,
    0x5b9c_ca4f,
    0x682e_6ff3,
    0x748f_82ee,
    0x78a5_636f,
    0x84c8_7814,
    0x8cc7_0208,
    0x90be_fffa,
    0xa450_6ceb,
    0xbef9_a3f7,
    0xc671_78f2,
  ];

  let mut h: [u32; 8] = [
    0x6a09_e667,
    0xbb67_ae85,
    0x3c6e_f372,
    0xa54f_f53a,
    0x510e_527f,
    0x9b05_688c,
    0x1f83_d9ab,
    0x5be0_cd19,
  ];

  let bit_len = (data.len() as u64) * 8;
  let mut msg = data.to_vec();
  msg.push(0x80);
  while (msg.len() % 64) != 56 {
    msg.push(0x00);
  }
  msg.extend_from_slice(&bit_len.to_be_bytes());

  let (chunks, _) = msg.as_chunks::<64>();
  for chunk in chunks {
    let mut w = [0u32; 64];
    for i in 0..16 {
      w[i] = u32::from_be_bytes([
        chunk[4 * i],
        chunk[4 * i + 1],
        chunk[4 * i + 2],
        chunk[4 * i + 3],
      ]);
    }
    for i in 16..64 {
      let s0 = w[i - 15].rotate_right(7)
        ^ w[i - 15].rotate_right(18)
        ^ (w[i - 15] >> 3);
      let s1 = w[i - 2].rotate_right(17)
        ^ w[i - 2].rotate_right(19)
        ^ (w[i - 2] >> 10);
      w[i] = w[i - 16]
        .wrapping_add(s0)
        .wrapping_add(w[i - 7])
        .wrapping_add(s1);
    }

    let mut a = h[0];
    let mut b = h[1];
    let mut c = h[2];
    let mut d = h[3];
    let mut e = h[4];
    let mut f = h[5];
    let mut g = h[6];
    let mut h_val = h[7];

    for i in 0..64 {
      let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
      let ch = (e & f) ^ ((!e) & g);
      let temp1 = h_val
        .wrapping_add(s1)
        .wrapping_add(ch)
        .wrapping_add(K[i])
        .wrapping_add(w[i]);
      let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
      let maj = (a & b) ^ (a & c) ^ (b & c);
      let temp2 = s0.wrapping_add(maj);

      h_val = g;
      g = f;
      f = e;
      e = d.wrapping_add(temp1);
      d = c;
      c = b;
      b = a;
      a = temp1.wrapping_add(temp2);
    }

    h[0] = h[0].wrapping_add(a);
    h[1] = h[1].wrapping_add(b);
    h[2] = h[2].wrapping_add(c);
    h[3] = h[3].wrapping_add(d);
    h[4] = h[4].wrapping_add(e);
    h[5] = h[5].wrapping_add(f);
    h[6] = h[6].wrapping_add(g);
    h[7] = h[7].wrapping_add(h_val);
  }

  let mut hex_str = String::with_capacity(64);
  for val in h {
    use std::fmt::Write;
    let _ = write!(hex_str, "{:08x}", val);
  }
  hex_str
}

/// Adds a provenance header containing the version and SHA-256 hash to workflow YAML content.
pub fn stamp_provenance_header(content: &str, version: &str) -> String {
  let hash = sha256_hex(content.as_bytes());
  format!(
    "# Generated by rsmk {version}. Safe to overwrite unless you have edited it.\n# rsmk:generated sha256={hash}\n\n{content}"
  )
}

/// Resolves candidate name from CLI arguments or prompts interactively.
pub fn resolve_candidate_name(name_arg: Option<&str>) -> String {
  if let Some(name) = name_arg {
    let trimmed = name.trim();
    if !trimmed.is_empty() {
      return trimmed.to_string();
    }
  }

  if std::io::stdin().is_terminal() && std::io::stdout().is_terminal() {
    use std::io::{self, Write};
    print!("Candidate name [Jane Doe]: ");
    let _ = io::stdout().flush();
    let mut input = String::new();
    if io::stdin().read_line(&mut input).is_ok() {
      let trimmed = input.trim();
      if !trimmed.is_empty() {
        return trimmed.to_string();
      }
    }
  }

  "Jane Doe".to_string()
}

/// Checks if the target directory is inside an existing git work tree.
pub fn is_inside_git_repo(dir: &Path) -> bool {
  std::process::Command::new("git")
    .args(["rev-parse", "--is-inside-work-tree"])
    .current_dir(dir)
    .output()
    .map(|output| {
      output.status.success()
        && String::from_utf8_lossy(&output.stdout).trim() == "true"
    })
    .unwrap_or(false)
}

/// Initializes a new git repository in the target directory.
pub fn init_git_repo(dir: &Path) -> Result<bool, String> {
  let output = std::process::Command::new("git")
    .arg("init")
    .current_dir(dir)
    .output()
    .map_err(|e| format!("Failed to run 'git init': {e}"))?;

  if !output.status.success() {
    let stderr = String::from_utf8_lossy(&output.stderr);
    return Err(format!("'git init' failed: {stderr}"));
  }
  Ok(true)
}

/// Ensures `.gitignore` exists and ignores `*.pdf` and `.resumake/`.
pub fn ensure_gitignore(dir: &Path) -> Result<(), String> {
  let gitignore_path = dir.join(".gitignore");
  let mut existing = if gitignore_path.exists() {
    fs::read_to_string(&gitignore_path)
      .map_err(|e| format!("Failed to read .gitignore: {e}"))?
  } else {
    String::new()
  };

  let has_pdf = existing.lines().any(|l| l.trim() == "*.pdf");
  let has_resumake = existing
    .lines()
    .any(|l| l.trim() == ".resumake/" || l.trim() == ".resumake");

  let mut modified = false;

  if !has_pdf {
    if !existing.is_empty() && !existing.ends_with('\n') {
      existing.push('\n');
    }
    existing.push_str("*.pdf\n");
    modified = true;
  }
  if !has_resumake {
    if !existing.is_empty() && !existing.ends_with('\n') {
      existing.push('\n');
    }
    existing.push_str(".resumake/\n");
    modified = true;
  }

  if modified || !gitignore_path.exists() {
    fs::write(&gitignore_path, existing)
      .map_err(|e| format!("Failed to write .gitignore: {e}"))?;
  }
  Ok(())
}

/// Ensures `.gitattributes` exists and contains `* text=auto eol=lf`.
pub fn ensure_gitattributes(dir: &Path) -> Result<(), String> {
  let gitattributes_path = dir.join(".gitattributes");
  let mut existing = if gitattributes_path.exists() {
    fs::read_to_string(&gitattributes_path)
      .map_err(|e| format!("Failed to read .gitattributes: {e}"))?
  } else {
    String::new()
  };

  let has_text_attr =
    existing.lines().any(|l| l.trim() == "* text=auto eol=lf");
  let mut modified = false;

  if !has_text_attr {
    if !existing.is_empty() && !existing.ends_with('\n') {
      existing.push('\n');
    }
    existing.push_str("* text=auto eol=lf\n");
    modified = true;
  }

  if modified || !gitattributes_path.exists() {
    fs::write(&gitattributes_path, existing)
      .map_err(|e| format!("Failed to write .gitattributes: {e}"))?;
  }
  Ok(())
}

/// Scaffolds `.github/workflows/ci.yml` and `.github/workflows/release.yml` with provenance headers.
pub fn scaffold_workflows(dir: &Path, force: bool) -> Result<(), String> {
  let workflows_dir = dir.join(".github").join("workflows");
  fs::create_dir_all(&workflows_dir)
    .map_err(|e| format!("Failed to create workflows directory: {e}"))?;

  let version = env!("CARGO_PKG_VERSION");

  let ci_path = workflows_dir.join("ci.yml");
  if !ci_path.exists() || force {
    let ci_content = generate_ci_workflow(None);
    let ci_with_header = stamp_provenance_header(&ci_content, version);
    fs::write(&ci_path, ci_with_header)
      .map_err(|e| format!("Failed to write CI workflow: {e}"))?;
  }

  let release_path = workflows_dir.join("release.yml");
  if !release_path.exists() || force {
    let release_content = generate_release_workflow(None);
    let release_with_header =
      stamp_provenance_header(&release_content, version);
    fs::write(&release_path, release_with_header)
      .map_err(|e| format!("Failed to write Release workflow: {e}"))?;
  }

  Ok(())
}

/// Checks if GitHub CLI `gh` is installed and authenticated.
pub fn is_gh_authenticated(dir: &Path) -> bool {
  if which::which("gh").is_err() {
    return false;
  }
  std::process::Command::new("gh")
    .args(["auth", "status"])
    .current_dir(dir)
    .output()
    .map(|output| output.status.success())
    .unwrap_or(false)
}

/// Handles interactive GitHub repository creation or prints remote setup guidance.
pub fn handle_github_remote(dir: &Path, quiet: bool) {
  if quiet {
    return;
  }

  let interactive =
    std::io::stdin().is_terminal() && std::io::stdout().is_terminal();

  if interactive && is_gh_authenticated(dir) {
    use std::io::{self, Write};
    print!("\nCreate a GitHub repository and push? [y/N]: ");
    let _ = io::stdout().flush();
    let mut input = String::new();
    if io::stdin().read_line(&mut input).is_ok() {
      let trimmed = input.trim().to_lowercase();
      if trimmed == "y" || trimmed == "yes" {
        let status = std::process::Command::new("gh")
          .args(["repo", "create", "--source=.", "--push"])
          .current_dir(dir)
          .status();
        match status {
          Ok(s) if s.success() => {
            print_success("GitHub repository created and pushed successfully.");
            return;
          }
          Ok(_) => {
            print_error("Failed to create GitHub repository via gh CLI.");
          }
          Err(e) => {
            print_error(&format!("Error running gh CLI: {e}"));
          }
        }
      }
    }
  }

  println!("\nNext steps to publish your résumé repository:");
  println!("  1. Track and commit your changes:");
  println!("     git add .");
  println!("     git commit -m \"feat: initial résumé scaffold\"");
  println!("  2. Push to GitHub:");
  println!("     gh repo create --source=. --push");
  println!("     # Or configure remote manually:");
  println!("     git remote add origin git@github.com:<username>/<repo>.git");
  println!("     git branch -M main");
  println!("     git push -u origin main");
}

/// Executes the full initialization command.
pub fn run_init(opts: InitOptions) -> Result<(), String> {
  if opts.output.exists() && !opts.force {
    return Err(format!(
      "File '{}' already exists. Use --force to overwrite.",
      opts.output.display()
    ));
  }

  let candidate_name = resolve_candidate_name(opts.name);
  let template_content = generate_init_template(&candidate_name);

  let base_dir = opts
    .output
    .parent()
    .filter(|p| !p.as_os_str().is_empty())
    .unwrap_or(Path::new("."));

  if !base_dir.exists() {
    fs::create_dir_all(base_dir).map_err(|e| e.to_string())?;
  }

  fs::write(opts.output, template_content).map_err(|e| e.to_string())?;
  if !opts.quiet {
    print_success(&format!(
      "Initialized new résumé content scaffold at '{}'",
      opts.output.display()
    ));
  }

  if !opts.no_git {
    if !is_inside_git_repo(base_dir) {
      match init_git_repo(base_dir) {
        Ok(_) => {
          if !opts.quiet {
            print_success("Initialized Git repository");
          }
        }
        Err(e) => {
          if !opts.quiet {
            print_info(&format!("Skipping 'git init': {e}"));
          }
        }
      }
    }
    ensure_gitignore(base_dir)?;
    ensure_gitattributes(base_dir)?;
    if !opts.quiet {
      print_success("Created .gitignore and .gitattributes");
    }
  }

  if !opts.no_workflows {
    scaffold_workflows(base_dir, opts.force)?;
    if !opts.quiet {
      print_success("Created GitHub Actions workflows in .github/workflows/");
    }
  }

  if !opts.no_git {
    handle_github_remote(base_dir, opts.quiet);
  }

  Ok(())
}

#[cfg(test)]
mod tests {
  use super::*;
  use tempfile::TempDir;

  #[test]
  fn test_sha256_hex() {
    assert_eq!(
      sha256_hex(b""),
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );
    assert_eq!(
      sha256_hex(b"abc"),
      "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
    assert_eq!(
      sha256_hex(b"The quick brown fox jumps over the lazy dog"),
      "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592"
    );
  }

  #[test]
  fn test_stamp_provenance_header() {
    let content = "name: CI\n";
    let stamped = stamp_provenance_header(content, "0.1.0");
    assert!(stamped.contains("# Generated by rsmk 0.1.0."));
    assert!(stamped.contains("# rsmk:generated sha256="));
    assert!(stamped.ends_with("name: CI\n"));
  }

  #[test]
  fn test_ensure_gitignore_and_attributes() {
    let temp = TempDir::new().unwrap();
    let dir = temp.path();

    ensure_gitignore(dir).unwrap();
    let gitignore = fs::read_to_string(dir.join(".gitignore")).unwrap();
    assert!(gitignore.contains("*.pdf"));
    assert!(gitignore.contains(".resumake/"));

    // Running again does not duplicate lines
    ensure_gitignore(dir).unwrap();
    let gitignore2 = fs::read_to_string(dir.join(".gitignore")).unwrap();
    assert_eq!(gitignore, gitignore2);

    ensure_gitattributes(dir).unwrap();
    let gitattributes = fs::read_to_string(dir.join(".gitattributes")).unwrap();
    assert!(gitattributes.contains("* text=auto eol=lf"));

    // Running again does not duplicate
    ensure_gitattributes(dir).unwrap();
    let gitattributes2 =
      fs::read_to_string(dir.join(".gitattributes")).unwrap();
    assert_eq!(gitattributes, gitattributes2);
  }

  #[test]
  fn test_scaffold_workflows() {
    let temp = TempDir::new().unwrap();
    let dir = temp.path();

    scaffold_workflows(dir, false).unwrap();
    let ci_path = dir.join(".github").join("workflows").join("ci.yml");
    let release_path =
      dir.join(".github").join("workflows").join("release.yml");

    assert!(ci_path.exists());
    assert!(release_path.exists());

    let ci_content = fs::read_to_string(ci_path).unwrap();
    assert!(ci_content.contains("# Generated by rsmk"));
    assert!(ci_content.contains("# rsmk:generated sha256="));
    assert!(ci_content.contains("name: CI"));

    let rel_content = fs::read_to_string(release_path).unwrap();
    assert!(rel_content.contains("# Generated by rsmk"));
    assert!(rel_content.contains("# rsmk:generated sha256="));
    assert!(rel_content.contains("name: Release"));
  }
}
