//! Initialization logic for scaffolding new résumé projects, git repositories,
//! and GitHub Actions workflows.

use crate::schema::{
  generate_ci_workflow, generate_init_template, generate_release_workflow,
};
use crate::ui::{print_error, print_info, print_success};
use std::fs;
use std::io::IsTerminal;
use std::path::{Path, PathBuf};

/// Options configuring the workspace initialization process.
#[derive(Debug, Clone)]
pub struct InitOptions<'a> {
  /// Explicit candidate name override.
  pub name: Option<&'a str>,
  /// Destination path for the new content file.
  pub output: &'a Path,
  /// Whether to overwrite existing files.
  pub force: bool,
  /// Whether to skip git repository initialization and git config files.
  pub no_git: bool,
  /// Whether to skip GitHub Actions workflow scaffolding.
  pub no_workflows: bool,
  /// Whether to update GitHub Actions workflow files.
  pub update: bool,
  /// Suppress informational console output.
  pub quiet: bool,
}

/// Computes the SHA-256 hash of a byte slice and returns it as a lowercase hex string.
pub fn sha256_hex(data: &[u8]) -> String {
  const K: [u32; 64] = [
    0x428a_2f98,
    0x7137_4491,
    0xb5c0_fbcf,
    0xe9b5_dba5,
    0x3956_c25b,
    0x59f1_11f1,
    0x923f_82a4,
    0xab1c_5ed5,
    0xd807_aa98,
    0x1283_5b01,
    0x2431_85be,
    0x550c_7dc3,
    0x72be_5d74,
    0x80de_b1fe,
    0x9bdc_06a7,
    0xc19b_f174,
    0xe49b_69c1,
    0xefbe_4786,
    0x0fc1_9dc6,
    0x240c_a1cc,
    0x2de9_2c6f,
    0x4a74_84aa,
    0x5cb0_a9dc,
    0x76f9_88da,
    0x983e_5152,
    0xa831_c66d,
    0xb003_27c8,
    0xbf59_7fc7,
    0xc6e0_0bf3,
    0xd5a7_9147,
    0x06ca_6351,
    0x1429_2967,
    0x27b7_0a85,
    0x2e1b_2138,
    0x4d2c_6dfc,
    0x5338_0d13,
    0x650a_7354,
    0x766a_0abb,
    0x81c2_c92e,
    0x9272_2c85,
    0xa2bf_e8a1,
    0xa81a_664b,
    0xc24b_8b70,
    0xc76c_51a3,
    0xd192_e819,
    0xd699_0624,
    0xf40e_3585,
    0x106a_a070,
    0x19a4_c116,
    0x1e37_6c08,
    0x2748_774c,
    0x34b0_bcb5,
    0x391c_0cb3,
    0x4ed8_aa4a,
    0x5b9c_ca4f,
    0x682e_6ff3,
    0x748f_82ee,
    0x78a5_636f,
    0x84c8_7814,
    0x8cc7_0208,
    0x90be_fffa,
    0xa450_6ceb,
    0xbef9_a3f7,
    0xc671_78f2,
  ];

  let mut h: [u32; 8] = [
    0x6a09_e667,
    0xbb67_ae85,
    0x3c6e_f372,
    0xa54f_f53a,
    0x510e_527f,
    0x9b05_688c,
    0x1f83_d9ab,
    0x5be0_cd19,
  ];

  let bit_len = (data.len() as u64) * 8;
  let mut msg = data.to_vec();
  msg.push(0x80);
  while (msg.len() % 64) != 56 {
    msg.push(0x00);
  }
  msg.extend_from_slice(&bit_len.to_be_bytes());

  let (chunks, _) = msg.as_chunks::<64>();
  for chunk in chunks {
    let mut w = [0u32; 64];
    for i in 0..16 {
      w[i] = u32::from_be_bytes([
        chunk[4 * i],
        chunk[4 * i + 1],
        chunk[4 * i + 2],
        chunk[4 * i + 3],
      ]);
    }
    for i in 16..64 {
      let s0 = w[i - 15].rotate_right(7)
        ^ w[i - 15].rotate_right(18)
        ^ (w[i - 15] >> 3);
      let s1 = w[i - 2].rotate_right(17)
        ^ w[i - 2].rotate_right(19)
        ^ (w[i - 2] >> 10);
      w[i] = w[i - 16]
        .wrapping_add(s0)
        .wrapping_add(w[i - 7])
        .wrapping_add(s1);
    }

    let mut a = h[0];
    let mut b = h[1];
    let mut c = h[2];
    let mut d = h[3];
    let mut e = h[4];
    let mut f = h[5];
    let mut g = h[6];
    let mut h_val = h[7];

    for i in 0..64 {
      let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
      let ch = (e & f) ^ ((!e) & g);
      let temp1 = h_val
        .wrapping_add(s1)
        .wrapping_add(ch)
        .wrapping_add(K[i])
        .wrapping_add(w[i]);
      let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
      let maj = (a & b) ^ (a & c) ^ (b & c);
      let temp2 = s0.wrapping_add(maj);

      h_val = g;
      g = f;
      f = e;
      e = d.wrapping_add(temp1);
      d = c;
      c = b;
      b = a;
      a = temp1.wrapping_add(temp2);
    }

    h[0] = h[0].wrapping_add(a);
    h[1] = h[1].wrapping_add(b);
    h[2] = h[2].wrapping_add(c);
    h[3] = h[3].wrapping_add(d);
    h[4] = h[4].wrapping_add(e);
    h[5] = h[5].wrapping_add(f);
    h[6] = h[6].wrapping_add(g);
    h[7] = h[7].wrapping_add(h_val);
  }

  let mut hex_str = String::with_capacity(64);
  for val in h {
    use std::fmt::Write;
    let _ = write!(hex_str, "{:08x}", val);
  }
  hex_str
}

/// Adds a provenance header containing the version and SHA-256 hash to workflow YAML content.
pub fn stamp_provenance_header(content: &str, version: &str) -> String {
  let hash = sha256_hex(content.as_bytes());
  format!(
    "# Generated by rsmk {version}. Safe to overwrite unless you have edited it.\n# rsmk:generated sha256={hash}\n\n{content}"
  )
}

/// Extracts the SHA-256 hash from `# rsmk:generated sha256=<HASH>` and the body below the header.
pub fn extract_provenance_and_body(content: &str) -> Option<(&str, &str)> {
  let prefix = "# rsmk:generated sha256=";
  let idx = content.find(prefix)?;
  let after_prefix = &content[idx + prefix.len()..];
  let end_of_line = after_prefix.find('\n').unwrap_or(after_prefix.len());
  let hash = after_prefix[..end_of_line].trim();
  let after_line = if end_of_line < after_prefix.len() {
    &after_prefix[end_of_line + 1..]
  } else {
    ""
  };

  let body = if let Some(stripped) = after_line.strip_prefix("\r\n") {
    stripped
  } else if let Some(stripped) = after_line.strip_prefix('\n') {
    stripped
  } else {
    after_line
  };

  Some((hash, body))
}

/// Generates a standard unified diff between two text documents.
pub fn generate_unified_diff(
  filename: &str,
  old_content: &str,
  new_content: &str,
) -> String {
  let old_lines: Vec<&str> = old_content.lines().collect();
  let new_lines: Vec<&str> = new_content.lines().collect();

  let m = old_lines.len();
  let n = new_lines.len();

  let mut dp = vec![vec![0u32; n + 1]; m + 1];
  for i in 1..=m {
    for j in 1..=n {
      if old_lines[i - 1] == new_lines[j - 1] {
        dp[i][j] = dp[i - 1][j - 1] + 1;
      } else {
        dp[i][j] = dp[i - 1][j].max(dp[i][j - 1]);
      }
    }
  }

  let mut diff_ops = Vec::new();
  let mut i = m;
  let mut j = n;

  while i > 0 || j > 0 {
    if i > 0 && j > 0 && old_lines[i - 1] == new_lines[j - 1] {
      diff_ops.push((' ', old_lines[i - 1]));
      i -= 1;
      j -= 1;
    } else if j > 0 && (i == 0 || dp[i][j - 1] >= dp[i - 1][j]) {
      diff_ops.push(('+', new_lines[j - 1]));
      j -= 1;
    } else if i > 0 && (j == 0 || dp[i][j - 1] < dp[i - 1][j]) {
      diff_ops.push(('-', old_lines[i - 1]));
      i -= 1;
    }
  }

  diff_ops.reverse();

  let mut out = String::new();
  out.push_str(&format!("--- {filename} (current)\n"));
  out.push_str(&format!("+++ {filename} (target)\n"));
  out.push_str(&format!("@@ -1,{m} +1,{n} @@\n"));

  for (op, line) in diff_ops {
    match op {
      '+' => out.push_str(&format!("+{line}\n")),
      '-' => out.push_str(&format!("-{line}\n")),
      _ => out.push_str(&format!(" {line}\n")),
    }
  }

  out
}

/// Returns true when `path` should be treated as an explicit content-file
/// target rather than a directory to scaffold inside.
///
/// An existing directory is never a file; an existing regular file always is.
/// For a path that does not yet exist, only a `.yaml`/`.yml` extension marks it
/// as a file — bare names like `arvin_resume` are treated as directories.
fn looks_like_file(path: &Path) -> bool {
  if path.is_dir() {
    return false;
  }
  if path.is_file() {
    return true;
  }
  matches!(
    path
      .extension()
      .and_then(|e| e.to_str())
      .map(str::to_ascii_lowercase)
      .as_deref(),
    Some("yaml") | Some("yml")
  )
}

/// Resolves the effective content-file path for `rsmk init` from the optional
/// positional destination and the optional `--output` flag (which are mutually
/// exclusive at the CLI layer).
///
/// - Neither given: `content.yaml` in the current directory.
/// - `--output <path>`: used verbatim.
/// - positional `<dest>`: a directory-like value scaffolds `<dest>/content.yaml`;
///   a `*.yaml` value is used verbatim as the file path.
pub fn resolve_init_output(
  dest: Option<&Path>,
  output: Option<&Path>,
) -> PathBuf {
  if let Some(output) = output {
    return output.to_path_buf();
  }
  match dest {
    None => PathBuf::from("content.yaml"),
    Some(dest) if looks_like_file(dest) => dest.to_path_buf(),
    Some(dest) => dest.join("content.yaml"),
  }
}

/// Returns true when `dir` exists and contains at least one entry.
fn dir_has_entries(dir: &Path) -> bool {
  match fs::read_dir(dir) {
    Ok(mut entries) => entries.next().is_some(),
    Err(_) => false,
  }
}

/// Resolves candidate name from CLI arguments or prompts interactively.
pub fn resolve_candidate_name(name_arg: Option<&str>) -> String {
  if let Some(name) = name_arg {
    let trimmed = name.trim();
    if !trimmed.is_empty() {
      return trimmed.to_string();
    }
  }

  if std::io::stdin().is_terminal() && std::io::stdout().is_terminal() {
    use std::io::{self, Write};
    print!("Candidate name [Jane Doe]: ");
    let _ = io::stdout().flush();
    let mut input = String::new();
    if io::stdin().read_line(&mut input).is_ok() {
      let trimmed = input.trim();
      if !trimmed.is_empty() {
        return trimmed.to_string();
      }
    }
  }

  "Jane Doe".to_string()
}

/// Checks if the target directory is inside an existing git work tree.
pub fn is_inside_git_repo(dir: &Path) -> bool {
  std::process::Command::new("git")
    .args(["rev-parse", "--is-inside-work-tree"])
    .current_dir(dir)
    .output()
    .map(|output| {
      output.status.success()
        && String::from_utf8_lossy(&output.stdout).trim() == "true"
    })
    .unwrap_or(false)
}

/// Initializes a new git repository in the target directory.
pub fn init_git_repo(dir: &Path) -> Result<bool, String> {
  let output = std::process::Command::new("git")
    .arg("init")
    .current_dir(dir)
    .output()
    .map_err(|e| format!("Failed to run 'git init': {e}"))?;

  if !output.status.success() {
    let stderr = String::from_utf8_lossy(&output.stderr);
    return Err(format!("'git init' failed: {stderr}"));
  }
  Ok(true)
}

/// Ensures `.gitignore` exists and ignores `*.pdf` and `.resumake/`.
pub fn ensure_gitignore(dir: &Path) -> Result<(), String> {
  let gitignore_path = dir.join(".gitignore");
  let mut existing = if gitignore_path.exists() {
    fs::read_to_string(&gitignore_path)
      .map_err(|e| format!("Failed to read .gitignore: {e}"))?
  } else {
    String::new()
  };

  let has_pdf = existing.lines().any(|l| l.trim() == "*.pdf");
  let has_resumake = existing
    .lines()
    .any(|l| l.trim() == ".resumake/" || l.trim() == ".resumake");

  let mut modified = false;

  if !has_pdf {
    if !existing.is_empty() && !existing.ends_with('\n') {
      existing.push('\n');
    }
    existing.push_str("*.pdf\n");
    modified = true;
  }
  if !has_resumake {
    if !existing.is_empty() && !existing.ends_with('\n') {
      existing.push('\n');
    }
    existing.push_str(".resumake/\n");
    modified = true;
  }

  if modified || !gitignore_path.exists() {
    fs::write(&gitignore_path, existing)
      .map_err(|e| format!("Failed to write .gitignore: {e}"))?;
  }
  Ok(())
}

/// Ensures `.gitattributes` exists and contains `* text=auto eol=lf`.
pub fn ensure_gitattributes(dir: &Path) -> Result<(), String> {
  let gitattributes_path = dir.join(".gitattributes");
  let mut existing = if gitattributes_path.exists() {
    fs::read_to_string(&gitattributes_path)
      .map_err(|e| format!("Failed to read .gitattributes: {e}"))?
  } else {
    String::new()
  };

  let has_text_attr =
    existing.lines().any(|l| l.trim() == "* text=auto eol=lf");
  let mut modified = false;

  if !has_text_attr {
    if !existing.is_empty() && !existing.ends_with('\n') {
      existing.push('\n');
    }
    existing.push_str("* text=auto eol=lf\n");
    modified = true;
  }

  if modified || !gitattributes_path.exists() {
    fs::write(&gitattributes_path, existing)
      .map_err(|e| format!("Failed to write .gitattributes: {e}"))?;
  }
  Ok(())
}

/// Scaffolds `.github/workflows/ci.yml` and `.github/workflows/release.yml` with provenance headers.
pub fn scaffold_workflows(dir: &Path, force: bool) -> Result<(), String> {
  let workflows_dir = dir.join(".github").join("workflows");
  fs::create_dir_all(&workflows_dir)
    .map_err(|e| format!("Failed to create workflows directory: {e}"))?;

  let version = env!("CARGO_PKG_VERSION");

  let ci_path = workflows_dir.join("ci.yml");
  if !ci_path.exists() || force {
    let ci_content = generate_ci_workflow(None);
    let ci_with_header = stamp_provenance_header(&ci_content, version);
    fs::write(&ci_path, ci_with_header)
      .map_err(|e| format!("Failed to write CI workflow: {e}"))?;
  }

  let release_path = workflows_dir.join("release.yml");
  if !release_path.exists() || force {
    let release_content = generate_release_workflow(None);
    let release_with_header =
      stamp_provenance_header(&release_content, version);
    fs::write(&release_path, release_with_header)
      .map_err(|e| format!("Failed to write Release workflow: {e}"))?;
  }

  Ok(())
}

/// Checks if GitHub CLI `gh` is installed and authenticated.
pub fn is_gh_authenticated(dir: &Path) -> bool {
  if which::which("gh").is_err() {
    return false;
  }
  std::process::Command::new("gh")
    .args(["auth", "status"])
    .current_dir(dir)
    .output()
    .map(|output| output.status.success())
    .unwrap_or(false)
}

/// Handles interactive GitHub repository creation or prints remote setup guidance.
pub fn handle_github_remote(dir: &Path, quiet: bool) {
  if quiet {
    return;
  }

  let interactive =
    std::io::stdin().is_terminal() && std::io::stdout().is_terminal();

  if interactive && is_gh_authenticated(dir) {
    use std::io::{self, Write};
    print!("\nCreate a GitHub repository and push? [y/N]: ");
    let _ = io::stdout().flush();
    let mut input = String::new();
    if io::stdin().read_line(&mut input).is_ok() {
      let trimmed = input.trim().to_lowercase();
      if trimmed == "y" || trimmed == "yes" {
        let status = std::process::Command::new("gh")
          .args(["repo", "create", "--source=.", "--push"])
          .current_dir(dir)
          .status();
        match status {
          Ok(s) if s.success() => {
            print_success("GitHub repository created and pushed successfully.");
            return;
          }
          Ok(_) => {
            print_error("Failed to create GitHub repository via gh CLI.");
          }
          Err(e) => {
            print_error(&format!("Error running gh CLI: {e}"));
          }
        }
      }
    }
  }

  println!("\nNext steps to publish your résumé repository:");
  println!("  1. Track and commit your changes:");
  println!("     git add .");
  println!("     git commit -m \"feat: initial résumé scaffold\"");
  println!("  2. Push to GitHub:");
  println!("     gh repo create --source=. --push");
  println!("     # Or configure remote manually:");
  println!("     git remote add origin git@github.com:<username>/<repo>.git");
  println!("     git branch -M main");
  println!("     git push -u origin main");
}

/// Updates GitHub Actions workflow files to match the current binary version.
///
/// If a workflow file contains local modifications (SHA-256 mismatch with provenance header),
/// the update is skipped and a warning with a unified diff is displayed, unless `force` is true.
pub fn update_workflows(
  dir: &Path,
  force: bool,
  quiet: bool,
) -> Result<(), String> {
  let workflows_dir = dir.join(".github").join("workflows");
  fs::create_dir_all(&workflows_dir)
    .map_err(|e| format!("Failed to create workflows directory: {e}"))?;

  let version = env!("CARGO_PKG_VERSION");
  let workflow_specs: [(&str, String); 2] = [
    ("ci.yml", generate_ci_workflow(None)),
    ("release.yml", generate_release_workflow(None)),
  ];

  for (filename, raw_template) in workflow_specs {
    let path = workflows_dir.join(filename);
    let new_with_header = stamp_provenance_header(&raw_template, version);

    if !path.exists() {
      fs::write(&path, &new_with_header).map_err(|e| {
        format!("Failed to write workflow '{}': {e}", path.display())
      })?;
      if !quiet {
        print_success(&format!(
          "Created workflow '{}' pinned to rsmk v{version}",
          path.display()
        ));
      }
      continue;
    }

    let existing = fs::read_to_string(&path).map_err(|e| {
      format!("Failed to read workflow '{}': {e}", path.display())
    })?;

    let is_clean = match extract_provenance_and_body(&existing) {
      Some((recorded_hash, body)) => {
        let actual_hash = sha256_hex(body.as_bytes());
        let actual_hash_normalized =
          sha256_hex(body.replace("\r\n", "\n").as_bytes());
        actual_hash.eq_ignore_ascii_case(recorded_hash)
          || actual_hash_normalized.eq_ignore_ascii_case(recorded_hash)
      }
      None => false,
    };

    if is_clean || force {
      fs::write(&path, &new_with_header).map_err(|e| {
        format!("Failed to write workflow '{}': {e}", path.display())
      })?;
      if !quiet {
        let prefix = if !is_clean && force {
          "Force updated"
        } else {
          "Updated"
        };
        print_success(&format!(
          "{prefix} workflow '{}' to rsmk v{version}",
          path.display()
        ));
      }
    } else {
      if !quiet {
        eprintln!(
          "warning: Workflow '{}' has local modifications; skipping update. Use --force to overwrite.",
          path.display()
        );
        let diff = generate_unified_diff(
          &path.display().to_string(),
          &existing,
          &new_with_header,
        );
        eprintln!("{diff}");
      }
    }
  }

  Ok(())
}

/// Inspects `.github/workflows/` for pinned `version: "<VER>"` values and emits a warning
/// if any pinned version differs from `local_version`.
pub fn check_workflow_version_skew(repo_dir: &Path, local_version: &str) {
  let workflows_dir = repo_dir.join(".github").join("workflows");
  if !workflows_dir.is_dir() {
    return;
  }

  let entries = match fs::read_dir(&workflows_dir) {
    Ok(entries) => entries,
    Err(_) => return,
  };

  use std::collections::BTreeSet;
  let mut skew_versions = BTreeSet::new();

  for entry in entries.flatten() {
    let path = entry.path();
    if let Some(ext) = path.extension() {
      if ext == "yml" || ext == "yaml" {
        if let Ok(content) = fs::read_to_string(&path) {
          for line in content.lines() {
            let trimmed = line.trim();
            if let Some(rest) = trimmed.strip_prefix("version:") {
              let val = rest.trim().trim_matches('"').trim_matches('\'').trim();
              if !val.is_empty()
                && val != "RSMK_VERSION"
                && val != local_version
              {
                skew_versions.insert(val.to_string());
              }
            }
          }
        }
      }
    }
  }

  for pinned in skew_versions {
    eprintln!(
      "warning: Repository workflows pin rsmk {pinned}, but your local binary is {local_version}.\n         Layout telemetry may measure geometry differently in CI.\n         Run `rsmk init --update` to synchronize your workflow pin."
    );
  }
}

/// Executes the full initialization command.
pub fn run_init(opts: InitOptions) -> Result<(), String> {
  let base_dir = opts
    .output
    .parent()
    .filter(|p| !p.as_os_str().is_empty())
    .unwrap_or(Path::new("."));

  if opts.update {
    return update_workflows(base_dir, opts.force, opts.quiet);
  }

  if opts.output.exists() && !opts.force {
    return Err(format!(
      "File '{}' already exists. Use --force to overwrite.",
      opts.output.display()
    ));
  }

  // Validate the target directory up front so a rejected init leaves the
  // filesystem untouched (no directories created, no files written).
  if !opts.force && dir_has_entries(base_dir) {
    return Err(format!(
      "Directory '{}' is not empty. Use --force to scaffold into it anyway.",
      base_dir.display()
    ));
  }

  let candidate_name = resolve_candidate_name(opts.name);
  let template_content = generate_init_template(&candidate_name);

  if !base_dir.exists() {
    fs::create_dir_all(base_dir).map_err(|e| e.to_string())?;
  }

  fs::write(opts.output, template_content).map_err(|e| e.to_string())?;
  if !opts.quiet {
    print_success(&format!(
      "Initialized new résumé content scaffold at '{}'",
      opts.output.display()
    ));
  }

  if !opts.no_git {
    if !is_inside_git_repo(base_dir) {
      match init_git_repo(base_dir) {
        Ok(_) => {
          if !opts.quiet {
            print_success("Initialized Git repository");
          }
        }
        Err(e) => {
          if !opts.quiet {
            print_info(&format!("Skipping 'git init': {e}"));
          }
        }
      }
    }
    ensure_gitignore(base_dir)?;
    ensure_gitattributes(base_dir)?;
    if !opts.quiet {
      print_success("Created .gitignore and .gitattributes");
    }
  }

  // GitHub Actions workflows only make sense inside a repository, so they are
  // scaffolded only when a git repo is being set up. A workspace created with
  // --no-git can add them later with `rsmk init --update`.
  if opts.no_git {
    if !opts.no_workflows && !opts.quiet {
      print_info(
        "Skipping GitHub Actions workflows (--no-git). Run `rsmk init --update` \
         from the project directory to add CI/Release workflows later.",
      );
    }
  } else if !opts.no_workflows {
    scaffold_workflows(base_dir, opts.force)?;
    if !opts.quiet {
      print_success("Created GitHub Actions workflows in .github/workflows/");
    }
  }

  if !opts.no_git {
    handle_github_remote(base_dir, opts.quiet);
  }

  Ok(())
}

#[cfg(test)]
mod tests {
  use super::*;
  use tempfile::TempDir;

  #[test]
  fn test_sha256_hex() {
    assert_eq!(
      sha256_hex(b""),
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    );
    assert_eq!(
      sha256_hex(b"abc"),
      "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    );
    assert_eq!(
      sha256_hex(b"The quick brown fox jumps over the lazy dog"),
      "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592"
    );
  }

  #[test]
  fn test_stamp_provenance_header() {
    let content = "name: CI\n";
    let stamped = stamp_provenance_header(content, "0.1.0");
    assert!(stamped.contains("# Generated by rsmk 0.1.0."));
    assert!(stamped.contains("# rsmk:generated sha256="));
    assert!(stamped.ends_with("name: CI\n"));
  }

  #[test]
  fn test_ensure_gitignore_and_attributes() {
    let temp = TempDir::new().unwrap();
    let dir = temp.path();

    ensure_gitignore(dir).unwrap();
    let gitignore = fs::read_to_string(dir.join(".gitignore")).unwrap();
    assert!(gitignore.contains("*.pdf"));
    assert!(gitignore.contains(".resumake/"));

    // Running again does not duplicate lines
    ensure_gitignore(dir).unwrap();
    let gitignore2 = fs::read_to_string(dir.join(".gitignore")).unwrap();
    assert_eq!(gitignore, gitignore2);

    ensure_gitattributes(dir).unwrap();
    let gitattributes = fs::read_to_string(dir.join(".gitattributes")).unwrap();
    assert!(gitattributes.contains("* text=auto eol=lf"));

    // Running again does not duplicate
    ensure_gitattributes(dir).unwrap();
    let gitattributes2 =
      fs::read_to_string(dir.join(".gitattributes")).unwrap();
    assert_eq!(gitattributes, gitattributes2);
  }

  #[test]
  fn test_scaffold_workflows() {
    let temp = TempDir::new().unwrap();
    let dir = temp.path();

    scaffold_workflows(dir, false).unwrap();
    let ci_path = dir.join(".github").join("workflows").join("ci.yml");
    let release_path =
      dir.join(".github").join("workflows").join("release.yml");

    assert!(ci_path.exists());
    assert!(release_path.exists());

    let ci_content = fs::read_to_string(ci_path).unwrap();
    assert!(ci_content.contains("# Generated by rsmk"));
    assert!(ci_content.contains("# rsmk:generated sha256="));
    assert!(ci_content.contains("name: CI"));

    let rel_content = fs::read_to_string(release_path).unwrap();
    assert!(rel_content.contains("# Generated by rsmk"));
    assert!(rel_content.contains("# rsmk:generated sha256="));
    assert!(rel_content.contains("name: Release"));
  }

  #[test]
  fn test_extract_provenance_and_body() {
    let content = "name: CI\non: [push]\n";
    let stamped = stamp_provenance_header(content, "0.1.0");
    let (hash, body) = extract_provenance_and_body(&stamped).unwrap();
    assert_eq!(hash, sha256_hex(content.as_bytes()));
    assert_eq!(body, content);

    // Test with CRLF
    let stamped_crlf = stamped.replace('\n', "\r\n");
    let (hash_crlf, body_crlf) =
      extract_provenance_and_body(&stamped_crlf).unwrap();
    assert_eq!(hash_crlf, sha256_hex(content.as_bytes()));
    assert_eq!(body_crlf.replace("\r\n", "\n"), content);

    // Test missing header
    assert_eq!(extract_provenance_and_body("name: CI\n"), None);
  }

  #[test]
  fn test_generate_unified_diff() {
    let old_text = "line1\nline2\nline3\n";
    let new_text = "line1\nline2_modified\nline3\nline4\n";
    let diff = generate_unified_diff("test.yml", old_text, new_text);
    assert!(diff.contains("--- test.yml (current)"));
    assert!(diff.contains("+++ test.yml (target)"));
    assert!(diff.contains("-line2"));
    assert!(diff.contains("+line2_modified"));
    assert!(diff.contains("+line4"));
  }

  #[test]
  fn test_update_workflows_clean_and_modified_and_force() {
    let temp = TempDir::new().unwrap();
    let dir = temp.path();
    let workflows_dir = dir.join(".github").join("workflows");
    fs::create_dir_all(&workflows_dir).unwrap();

    let ci_path = workflows_dir.join("ci.yml");
    let release_path = workflows_dir.join("release.yml");

    // 1. Scaffold initial workflows with version 0.0.1
    let old_ci_body = generate_ci_workflow(Some("0.0.1"));
    let old_ci_stamped = stamp_provenance_header(&old_ci_body, "0.0.1");
    fs::write(&ci_path, old_ci_stamped).unwrap();

    let old_release_body = generate_release_workflow(Some("0.0.1"));
    let old_release_stamped =
      stamp_provenance_header(&old_release_body, "0.0.1");
    fs::write(&release_path, old_release_stamped).unwrap();

    // 2. Clean update should update both to current version
    update_workflows(dir, false, true).unwrap();

    let current_version = env!("CARGO_PKG_VERSION");
    let updated_ci = fs::read_to_string(&ci_path).unwrap();
    assert!(
      updated_ci.contains(&format!("Generated by rsmk {current_version}"))
    );
    assert!(updated_ci.contains(&format!("version: \"{current_version}\"")));

    let updated_release = fs::read_to_string(&release_path).unwrap();
    assert!(
      updated_release.contains(&format!("Generated by rsmk {current_version}"))
    );
    assert!(
      updated_release.contains(&format!("version: \"{current_version}\""))
    );

    // 3. User modifies CI workflow
    let modified_ci =
      format!("{updated_ci}\n      - run: echo 'custom step'\n");
    fs::write(&ci_path, &modified_ci).unwrap();

    // Update without force should skip CI and keep user modification
    update_workflows(dir, false, true).unwrap();
    let ci_after_skip = fs::read_to_string(&ci_path).unwrap();
    assert_eq!(ci_after_skip, modified_ci);

    // Update with force should overwrite CI
    update_workflows(dir, true, true).unwrap();
    let ci_after_force = fs::read_to_string(&ci_path).unwrap();
    assert!(!ci_after_force.contains("custom step"));
    assert!(
      ci_after_force.contains(&format!("Generated by rsmk {current_version}"))
    );
  }

  #[test]
  fn test_run_init_update_does_not_touch_content_yaml() {
    let temp = TempDir::new().unwrap();
    let dir = temp.path();
    let content_file = dir.join("content.yaml");
    fs::write(&content_file, "custom content").unwrap();

    let workflows_dir = dir.join(".github").join("workflows");
    fs::create_dir_all(&workflows_dir).unwrap();
    let ci_path = workflows_dir.join("ci.yml");
    let old_ci =
      stamp_provenance_header(&generate_ci_workflow(Some("0.0.1")), "0.0.1");
    fs::write(&ci_path, old_ci).unwrap();

    run_init(InitOptions {
      name: None,
      output: &content_file,
      force: false,
      no_git: true,
      no_workflows: false,
      update: true,
      quiet: true,
    })
    .unwrap();

    // Verify content.yaml untouched
    assert_eq!(fs::read_to_string(&content_file).unwrap(), "custom content");

    // Verify CI workflow updated
    let updated_ci = fs::read_to_string(&ci_path).unwrap();
    let current_version = env!("CARGO_PKG_VERSION");
    assert!(
      updated_ci.contains(&format!("Generated by rsmk {current_version}"))
    );
  }
}
